[tool.black]
line-length = 99
target-version = ['py38']

#[tool.isort]
#profile = 'google'
#multi_line_output = 3
#include_trailing_comma = true
#force_grid_wrap = 0
#use_parentheses = true
#line_length = 99
#combine_as_imports = true
#known_first_party = ['src']
#known_third_party = ['aiogram', 'aiohttp', 'requests', 'beautifulsoup4']